// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NzmsaPhase2BackendAPI.Models;

namespace NzmsaPhase2BackendAPI.Migrations
{
    [DbContext(typeof(AppDatabase))]
    partial class AppDatabaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NzmsaPhase2BackendAPI.Models.Canvas", b =>
                {
                    b.Property<int>("CanvasID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("CanvasID");

                    b.ToTable("Canvas");
                });

            modelBuilder.Entity("NzmsaPhase2BackendAPI.Models.ColorData", b =>
                {
                    b.Property<int>("ColorDataID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CanvasID")
                        .HasColumnType("int");

                    b.Property<int>("ColumnIndex")
                        .HasColumnType("int");

                    b.Property<string>("Hex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RowIndex")
                        .HasColumnType("int");

                    b.HasKey("ColorDataID");

                    b.HasIndex("CanvasID");

                    b.ToTable("ColorData");
                });

            modelBuilder.Entity("NzmsaPhase2BackendAPI.Models.ColorData", b =>
                {
                    b.HasOne("NzmsaPhase2BackendAPI.Models.Canvas", null)
                        .WithMany("ColorData")
                        .HasForeignKey("CanvasID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
